AP_DISTRICTS = [
    {"name": "Visakhapatnam", "top_crop": "Rice, Cashew, Coffee", "avg_yield": "24.3 q/acre", "active_farmers": 8420, "common_pest": "Leaf Folder", "review_count": 3102, "density": "high", "zone": "North Coastal"},
    {"name": "Vizianagaram", "top_crop": "Rice, Sugarcane", "avg_yield": "19.8 q/acre", "active_farmers": 5230, "common_pest": "Stem Borer", "review_count": 1890, "density": "medium", "zone": "North Coastal"},
    {"name": "Srikakulam", "top_crop": "Rice, Groundnut", "avg_yield": "18.4 q/acre", "active_farmers": 4780, "common_pest": "BPH", "review_count": 1560, "density": "medium", "zone": "North Coastal"},
    {"name": "East Godavari", "top_crop": "BPT-5204 Rice, Coconut", "avg_yield": "28.1 q/acre", "active_farmers": 12340, "common_pest": "Rice Blast", "review_count": 4890, "density": "high", "zone": "Godavari Delta"},
    {"name": "West Godavari", "top_crop": "BPT-5204 Rice, Oil Palm", "avg_yield": "27.6 q/acre", "active_farmers": 11890, "common_pest": "BPH", "review_count": 4560, "density": "high", "zone": "Godavari Delta"},
    {"name": "Krishna", "top_crop": "Rice, Tobacco, Sugarcane", "avg_yield": "26.2 q/acre", "active_farmers": 10230, "common_pest": "BPH (HIGH)", "review_count": 4120, "density": "high", "zone": "Krishna Delta"},
    {"name": "Guntur", "top_crop": "Cotton, Chilli, Rice", "avg_yield": "22.4 q/acre", "active_farmers": 9870, "common_pest": "Bollworm", "review_count": 3780, "density": "high", "zone": "Krishna Delta"},
    {"name": "Prakasam", "top_crop": "Cotton, Groundnut, Tobacco", "avg_yield": "16.8 q/acre", "active_farmers": 7230, "common_pest": "Whitefly", "review_count": 2890, "density": "medium", "zone": "South Coastal"},
    {"name": "Nellore", "top_crop": "Rice, Aquaculture, Groundnut", "avg_yield": "20.3 q/acre", "active_farmers": 6780, "common_pest": "Leaf Roller", "review_count": 2340, "density": "medium", "zone": "South Coastal"},
    {"name": "Kurnool", "top_crop": "Groundnut, Cotton, Jowar", "avg_yield": "14.2 q/acre", "active_farmers": 8120, "common_pest": "Aphids", "review_count": 2780, "density": "medium", "zone": "Rayalaseema"},
    {"name": "Kadapa", "top_crop": "Groundnut, Tomato, Cotton", "avg_yield": "13.8 q/acre", "active_farmers": 6340, "common_pest": "Thrips", "review_count": 2120, "density": "medium", "zone": "Rayalaseema"},
    {"name": "Anantapur", "top_crop": "Groundnut, Cotton, Sunflower", "avg_yield": "12.1 q/acre", "active_farmers": 9230, "common_pest": "Spodoptera", "review_count": 3120, "density": "low", "zone": "Rayalaseema"},
    {"name": "Chittoor", "top_crop": "Groundnut, Mango, Rice", "avg_yield": "15.6 q/acre", "active_farmers": 7890, "common_pest": "Leaf Miner", "review_count": 2560, "density": "medium", "zone": "Rayalaseema"},
    {"name": "Alluri Sitarama Raju", "top_crop": "Coffee, Paddy, Turmeric", "avg_yield": "16.2 q/acre", "active_farmers": 3120, "common_pest": "White Grub", "review_count": 890, "density": "low", "zone": "Agency"},
    {"name": "Parvathipuram Manyam", "top_crop": "Paddy, Cashew, Mango", "avg_yield": "14.8 q/acre", "active_farmers": 2340, "common_pest": "Tea Mosquito Bug", "review_count": 670, "density": "low", "zone": "Agency"},
    {"name": "Anakapalli", "top_crop": "Rice, Sugarcane, Cashew", "avg_yield": "21.4 q/acre", "active_farmers": 5670, "common_pest": "Stem Borer", "review_count": 1780, "density": "medium", "zone": "North Coastal"},
    {"name": "Kakinada", "top_crop": "Rice, Coconut, Banana", "avg_yield": "25.8 q/acre", "active_farmers": 7890, "common_pest": "Rice Bug", "review_count": 2890, "density": "high", "zone": "Godavari Delta"},
    {"name": "Konaseema", "top_crop": "Rice, Coconut, Oil Palm", "avg_yield": "26.4 q/acre", "active_farmers": 6780, "common_pest": "BPH", "review_count": 2340, "density": "high", "zone": "Godavari Delta"},
    {"name": "Eluru", "top_crop": "Rice, Cotton, Sugarcane", "avg_yield": "23.6 q/acre", "active_farmers": 8120, "common_pest": "Leafhopper", "review_count": 2780, "density": "high", "zone": "Krishna Delta"},
    {"name": "NTR (Vijayawada)", "top_crop": "Rice, Vegetables, Banana", "avg_yield": "24.1 q/acre", "active_farmers": 7340, "common_pest": "Aphids", "review_count": 2560, "density": "high", "zone": "Krishna Delta"},
    {"name": "Palnadu", "top_crop": "Cotton, Rice, Groundnut", "avg_yield": "17.3 q/acre", "active_farmers": 6120, "common_pest": "Bollworm", "review_count": 2120, "density": "medium", "zone": "Krishna Delta"},
    {"name": "Bapatla", "top_crop": "Rice, Aquaculture, Chilli", "avg_yield": "22.8 q/acre", "active_farmers": 5890, "common_pest": "BPH (medium)", "review_count": 1980, "density": "medium", "zone": "South Coastal"},
    {"name": "Sri Sathya Sai", "top_crop": "Groundnut, Tomato, Paddy", "avg_yield": "13.4 q/acre", "active_farmers": 5230, "common_pest": "White Fly", "review_count": 1670, "density": "low", "zone": "Rayalaseema"},
    {"name": "Nandyal", "top_crop": "Groundnut, Cotton, Jowar", "avg_yield": "14.6 q/acre", "active_farmers": 6780, "common_pest": "Aphids", "review_count": 2230, "density": "medium", "zone": "Rayalaseema"},
    {"name": "Tirupati", "top_crop": "Groundnut, Sugarcane, Paddy", "avg_yield": "15.2 q/acre", "active_farmers": 5120, "common_pest": "Thrips", "review_count": 1780, "density": "medium", "zone": "Rayalaseema"},
    {"name": "Annamayya", "top_crop": "Groundnut, Tomato, Mango", "avg_yield": "13.9 q/acre", "active_farmers": 4230, "common_pest": "Fruit Borer", "review_count": 1340, "density": "low", "zone": "Rayalaseema"},
]

CROPS_DATA = [
    {"name": "BPT-5204 Rice", "variety": "BPT-5204", "season": "kharif", "rating": 4.8, "review_count": 4341, "water_need": "high", "temp_min": 25, "temp_max": 35, "rainfall_min": 1100, "rainfall_max": 1500, "humidity_min": 70, "humidity_max": 85, "growing_period": "June–November"},
    {"name": "NW-301 Wheat", "variety": "NW-301", "season": "rabi", "rating": 4.6, "review_count": 2203, "water_need": "low", "temp_min": 10, "temp_max": 22, "rainfall_min": 400, "rainfall_max": 650, "humidity_min": 40, "humidity_max": 60, "growing_period": "November–March"},
    {"name": "Reddy Cotton", "variety": "RCH-2", "season": "kharif", "rating": 4.1, "review_count": 2540, "water_need": "medium", "temp_min": 21, "temp_max": 30, "rainfall_min": 500, "rainfall_max": 800, "humidity_min": 50, "humidity_max": 70, "growing_period": "June–December"},
    {"name": "AP Groundnut", "variety": "TMV-2", "season": "kharif", "rating": 4.3, "review_count": 3120, "water_need": "low", "temp_min": 20, "temp_max": 30, "rainfall_min": 400, "rainfall_max": 700, "humidity_min": 40, "humidity_max": 65, "growing_period": "June–October"},
    {"name": "Guntur Chilli", "variety": "LCA-206", "season": "kharif", "rating": 4.5, "review_count": 1890, "water_need": "medium", "temp_min": 18, "temp_max": 28, "rainfall_min": 600, "rainfall_max": 900, "humidity_min": 55, "humidity_max": 70, "growing_period": "July–February"},
    {"name": "Sunflower K-84", "variety": "K-84", "season": "summer", "rating": 4.0, "review_count": 987, "water_need": "low", "temp_min": 18, "temp_max": 28, "rainfall_min": 350, "rainfall_max": 500, "humidity_min": 30, "humidity_max": 55, "growing_period": "January–May"},
    {"name": "Krishna Tobacco", "variety": "Flue-Cured", "season": "rabi", "rating": 3.9, "review_count": 1120, "water_need": "medium", "temp_min": 15, "temp_max": 28, "rainfall_min": 500, "rainfall_max": 750, "humidity_min": 45, "humidity_max": 65, "growing_period": "December–April"},
    {"name": "Vizag Coffee", "variety": "Arabica", "season": "kharif", "rating": 4.4, "review_count": 560, "water_need": "high", "temp_min": 15, "temp_max": 25, "rainfall_min": 1200, "rainfall_max": 2000, "humidity_min": 70, "humidity_max": 90, "growing_period": "Year-round"},
]

REVIEWS_DATA = [
    {
        "id": 1,
        "crop_name": "BPT-5204 Rice",
        "farmer_name": "Mahesh Reddy",
        "initials": "MR",
        "location": "East Godavari",
        "season": "Kharif",
        "avatar_color": "#3B6D11",
        "yield_rating": 5,
        "pest_rating": 5,
        "water_rating": 4,
        "profit_rating": 5,
        "review_text": "Excellent variety — 28 quintals/acre with minimal inputs. Pest resistance was outstanding despite BPH pressure in surrounding villages. Godavari delta soil suits this crop perfectly.",
        "tags": ["high yield", "pest resistant", "water efficient", "high profit"],
        "upvotes": 142,
        "comments": 12,
        "time_ago": "2h ago",
    },
    {
        "id": 2,
        "crop_name": "Guntur Chilli LCA-206",
        "farmer_name": "Suresh Naidu",
        "initials": "SN",
        "location": "Guntur",
        "season": "Kharif",
        "avatar_color": "#BA7517",
        "yield_rating": 4,
        "pest_rating": 3,
        "water_rating": 4,
        "profit_rating": 5,
        "review_text": "Best chilli season in 5 years. LCA-206 gave 800kg dry chilli/acre. Thrips were a concern in September but 2 sprays controlled them. Market price was excellent — ₹180/kg.",
        "tags": ["profitable", "high market price", "thrips manageable"],
        "upvotes": 98,
        "comments": 7,
        "time_ago": "5h ago",
    },
    {
        "id": 3,
        "crop_name": "AP Groundnut TMV-2",
        "farmer_name": "Padma Lakshmi",
        "initials": "PL",
        "location": "Anantapur",
        "season": "Kharif",
        "avatar_color": "#185FA5",
        "yield_rating": 4,
        "pest_rating": 4,
        "water_rating": 5,
        "profit_rating": 4,
        "review_text": "TMV-2 groundnut is drought-tolerant — survived the dry August well. Yield was 12 quintals/acre which is excellent for Anantapur region. Minimal irrigation needed.",
        "tags": ["drought tolerant", "low water", "good for Rayalaseema"],
        "upvotes": 76,
        "comments": 9,
        "time_ago": "1d ago",
    },
]

PESTS_DATA = [
    {
        "name": "Brown Planthopper (BPH)",
        "severity": "high",
        "severity_pct": 85,
        "affected_districts": "Krishna, Guntur, West Godavari",
        "acres_affected": 4100,
        "report_count": 63,
        "remedy": "Buprofezin 25 SC @ 800ml/acre + drain standing water. Avoid nitrogen excess. Plant resistant varieties like IR-64 next cycle.",
        "remedy_rating": 4.6,
        "remedy_votes": 234,
    },
    {
        "name": "Rice Blast (Pyricularia oryzae)",
        "severity": "medium",
        "severity_pct": 55,
        "affected_districts": "East Godavari, Kakinada",
        "acres_affected": 1800,
        "report_count": 28,
        "remedy": "Tricyclazole 75 WP @ 300g/acre at boot stage. Improve drainage. Avoid evening irrigation during humid spells.",
        "remedy_rating": 4.3,
        "remedy_votes": 89,
    },
    {
        "name": "Cotton Bollworm",
        "severity": "medium",
        "severity_pct": 50,
        "affected_districts": "Guntur, Prakasam, Kurnool",
        "acres_affected": 2300,
        "report_count": 41,
        "remedy": "Emamectin benzoate 5 SG @ 200g/acre. Install pheromone traps. Intercrop with marigold as trap crop.",
        "remedy_rating": 4.1,
        "remedy_votes": 156,
    },
    {
        "name": "Chilli Thrips (Scirtothrips dorsalis)",
        "severity": "medium",
        "severity_pct": 45,
        "affected_districts": "Guntur, Krishna, Prakasam",
        "acres_affected": 980,
        "report_count": 19,
        "remedy": "Spinosad 45 SC @ 125ml/acre. Remove infested leaves. Install blue sticky traps at 20/acre density.",
        "remedy_rating": 4.0,
        "remedy_votes": 72,
    },
    {
        "name": "Groundnut Leaf Miner",
        "severity": "low",
        "severity_pct": 22,
        "affected_districts": "Anantapur, Kurnool",
        "acres_affected": 340,
        "report_count": 8,
        "remedy": "Chlorantraniliprole 18.5 SC @ 150ml/acre. Light traps at 1/acre. Remove and destroy fallen leaves.",
        "remedy_rating": 3.9,
        "remedy_votes": 41,
    },
]

FORUM_DATA = [
    {
        "id": 1,
        "question": "How to manage BPH in standing water without draining the entire field in Krishna district?",
        "author": "Dr. Venkat Rao",
        "author_role": "Entomologist, ANGRAU",
        "badge": "expert",
        "topic": "Pest Control",
        "views": 3341,
        "answers": 34,
        "likes": 289,
    },
    {
        "id": 2,
        "question": "Is BPT-5204 or Konaseema Sona better for sandy loam soil in West Godavari?",
        "author": "Ranga Rao",
        "author_role": "22 years farming · Eluru",
        "badge": "trusted",
        "topic": "Rice",
        "views": 2892,
        "answers": 21,
        "likes": 134,
    },
    {
        "id": 3,
        "question": "When is the right time to apply potash for Guntur chilli during Kharif season?",
        "author": "ANGRAU Extension",
        "author_role": "Official Extension Service",
        "badge": "expert",
        "topic": "Rice",
        "views": 1893,
        "answers": 9,
        "likes": 97,
    },
    {
        "id": 4,
        "question": "Can groundnut and pigeonpea be successfully intercropped in Anantapur's red sandy soils?",
        "author": "Lakshmi Devi",
        "author_role": "Progressive Farmer · Anantapur",
        "badge": "trusted",
        "topic": "Irrigation",
        "views": 1201,
        "answers": 14,
        "likes": 82,
    },
    {
        "id": 5,
        "question": "What micro-irrigation subsidy schemes are available for drip irrigation in Rayalaseema districts?",
        "author": "AP Horticulture Dept",
        "author_role": "Government · Official",
        "badge": "expert",
        "topic": "Irrigation",
        "views": 4210,
        "answers": 6,
        "likes": 341,
    },
]

ALERTS_DATA = [
    {
        "title": "BPH Outbreak — Krishna & Guntur Districts",
        "body": "Brown Planthopper severity is HIGH within 60km radius. 63 reports in last 24h. Preventive spray recommended this week before rains arrive.",
        "type": "pest",
        "unread": True,
        "time_ago": "2 hours ago",
        "icon": "ti-bug",
    },
    {
        "title": "IMD Orange Alert · East Godavari",
        "body": "Heavy to very heavy rain forecast Thu–Sat (120–180mm). Avoid spraying Wednesday. Ensure field drainage is clear. Paddy harvesting should be expedited.",
        "type": "weather",
        "unread": True,
        "time_ago": "4 hours ago",
        "icon": "ti-cloud-storm",
    },
    {
        "title": "MSP Update — Paddy 2024–25",
        "body": "Government announces new MSP for Common Grade Paddy at ₹2,300/quintal and Grade A at ₹2,320/quintal for Kharif 2024–25 season.",
        "type": "policy",
        "unread": True,
        "time_ago": "Yesterday",
        "icon": "ti-file-invoice",
    },
    {
        "title": "Dr. Venkat Rao replied to your question",
        "body": "For BPH management without drainage, split-apply Buprofezin in the morning. Results are equally effective in field trials across Krishna delta...",
        "type": "reply",
        "unread": False,
        "time_ago": "2 days ago",
        "icon": "ti-message-2",
    },
    {
        "title": "Your review got 50 upvotes",
        "body": "Your BPT-5204 review from East Godavari has been upvoted 50 times and tagged as 'Top Review' for this variety this season.",
        "type": "community",
        "unread": False,
        "time_ago": "3 days ago",
        "icon": "ti-star",
    },
]

YIELD_DATA = {
    "varieties": [
        {"name": "BPT-5204", "yield": 28.2, "pct": 94},
        {"name": "Konaseema Sona", "yield": 25.8, "pct": 86},
        {"name": "MTU-1010", "yield": 22.4, "pct": 75},
        {"name": "IR-64", "yield": 19.8, "pct": 66},
        {"name": "Swarna", "yield": 17.3, "pct": 58},
    ],
    "profits": [
        {"name": "Guntur Chilli", "profit": "₹48,200", "pct": 96, "roi": "182%"},
        {"name": "Cotton", "profit": "₹32,400", "pct": 65, "roi": "148%"},
        {"name": "BPT Rice", "profit": "₹28,900", "pct": 58, "roi": "132%"},
        {"name": "Groundnut", "profit": "₹24,100", "pct": 48, "roi": "124%"},
        {"name": "Wheat", "profit": "₹21,200", "pct": 42, "roi": "118%"},
        {"name": "Tobacco", "profit": "₹18,700", "pct": 37, "roi": "109%"},
    ],
    "roi_leaders": [
        {"name": "Guntur Chilli", "roi": "182%"},
        {"name": "Cotton", "roi": "148%"},
        {"name": "BPT-5204 Rice", "roi": "132%"},
    ],
}
